engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
  - app/**
  - lib/**
exclude_paths:
- "jasmine/lib"
- "lib"
- "src/lib"
- "src/css"
- "src/fonts"
- "node_modules"
