engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
  - app/**
  - lib/**
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- "jasmine/lib/jasmine-2.3.4/jasmine.js"
- "jasmine/lib/jasmine-2.3.4/jasmine-html.js"
- "jasmine/spec/tests/index-test-spec1.js"